/* CODEHEAL DATABASE */
CREATE SCHEMA IF NOT EXISTS CodeHeal;

/* USE CODEHEAL DATABASE */
USE CodeHeal;

/* USERS TABLE */
CREATE TABLE users(id int auto_increment PRIMARY KEY, FullName VARCHAR(30) NOT NULL, MobileNumber INT NOT NULL, Email VARCHAR(30) NOT NULL,Password VARCHAR(200) NOT NULL, date DateTime NOT NULL);

/* USERS TABLE  OPTIMIZATIONS */
CREATE INDEX idx_FullName ON users(FullName);